### ISSUE TITLE
[FEATURE] Select Resolution

### ISSUE THREAD

**Issue by Marv2190** [n0201/TheTubeVideoAudioDownloader#1]
Can i somehow select the Resolution? The Downloader only downloads in low Quality - the Source has up to 4k.

**Comment by n0201** [comment]
pytube has a get_highest_resolution option, which i implemented. unfortunately it does not work with 4k. the resolution seems to be 1080p but im not sure (could also be 720p). I'll try to resolve that issue later on.

**Comment by n0201** [comment]
Option got added in V1.2 as Beta as I need to merge the audio and the video file which will be downloaded. this proccess is a bit slow, but it works. might change the method later on
